# ledger-registration.yaml

# The URL of your homeserver
hs_url: "http://your-homeserver.com:8008"

# An ID which is unique across all application services on your homeserver. This should never be changed once set.
id: "appservice-ledger"

# this is the base URL of the application service
url: "http://appservice-ledger:8080"

# This is the token that the AS should use as its access_token when using the Client-Server API
# This can be anything you want.
as_token: CHANGE_ME

# This is the token that the HS will use when sending requests to the AS.
# This can be anything you want.
hs_token: CHANGE_ME_TOO

# this is the local part of the desired user ID for this AS (in this case @ledger:your-homeserver.com)
sender_localpart: ledger

# Define the users and/or rooms that are allowed to interact with this AS here
namespaces:
  users:
    - exclusive: false
      regex: "@sombeody:your-homeserver.com"
    - exclusive: false
      regex: "@somebodyelse:your-homeserver.com"
  rooms: []
  aliases: []